name: Test
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        torch_ver: ["2.1.2"]
        modality: [image, text, audio, audio2text]
        include:
          - torch_ver: "2.1.2"
            torchvision_ver: "0.16.2"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |  # TODO: separate deps based on modality
          pip install torch==${{ matrix.torch_ver }} torchvision==${{ matrix.torchvision_ver }} torchaudio==${{ matrix.torch_ver }} --index-url https://download.pytorch.org/whl/cpu
          pip install requests pytest transformers librosa tiktoken einops sentencepiece timm
          pip install git+https://github.com/openai/whisper.git --no-deps
          pip install git+https://github.com/facebookresearch/encodec.git --no-deps

      - name: Run tests
        run: pytest -v tests/${{ matrix.modality }}
