name: Test
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install requests pytest transformers librosa
          pip install openai-whisper @ git+https://github.com/openai/whisper.git --no-deps
          pip install encodec @ git+https://github.com/facebookresearch/encodec.git --no-deps

      - name: Run tests
        run: pytest -v
