name: Test
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: setup.cfg
      - run: |
          pip install torch==2.0.* --extra-index-url https://download.pytorch.org/whl/cpu
          pip install .[dev]

      - name: Run tests
        run: pytest -v
