name: Test
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  test_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu
          pip install requests pytest timm tensorflow-cpu

      - name: Run tests
        run: pytest -v tests/image

  test_text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu
          pip install requests pytest transformers tiktoken sentencepiece msgpack

      - name: Run tests
        run: pytest -v tests/text

  test_audio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu
          pip install requests pytest transformers librosa einops
          pip install git+https://github.com/facebookresearch/encodec.git@0e2d0aed29362c8e8f52494baf3e6f99056b214f --no-deps

      - name: Run tests
        run: pytest -v tests/audio

  test_audio2text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu
          pip install requests pytest librosa tiktoken tqdm
          pip install git+https://github.com/openai/whisper.git@v20231117 --no-deps

      - name: Run tests
        run: pytest -v tests/audio2text
