name: Test
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        modality: [image, text, audio]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |  # TODO: separate deps based on modality
          pip install torch torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install requests pytest transformers librosa tiktoken einops sentencepiece timm
          pip install git+https://github.com/openai/whisper.git --no-deps
          pip install git+https://github.com/facebookresearch/encodec.git --no-deps

      - name: Run tests
        run: pytest -v tests/${{ matrix.modality }}
