name: Test
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: .github/requirements.txt
      - run: pip -r .github/requirements.txt

      - name: Run tests
        run: pytest -v
